name = "bison-tracker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 */6 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "bison-tracker-db"
database_id = "a044e3cc-bf5a-4342-a16c-30730f54691c"
